services:
  pgdatabase:
    image: postgres:14
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      # - POSTGRES_DB=airflow
      - TZ=Asia/Bangkok
      - PGTZ=Asia/Bangkok 
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - "./postgres:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U admin -d movielens"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5
    networks:
      - confluent

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8080:80"
    networks:
      - confluent

networks:
  confluent: