name: Build and Deploy Code

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-22.04
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: install python3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: upgrade pip
        run: python -m pip install --upgrade pip
      - name: install dependencies
        run: pip install -r requirements.txt