name: Build and Deploy Code

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-22.04
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: say hi to binhnt230
        run: echo "Hello binhnt230"